// This file is generated by 'pnpm move:get_abi'. DO NOT EDIT MANUALLY.
export const ACCESS_CONTROL_ABI = {
  address: "0x91bf586a77ca2e15193f8068d0f7e4f5e43253fc724be1fbc5efb6134a544180",
  name: "access_control",
  friends: [],
  exposed_functions: [
    {
      name: "assert_is_admin",
      visibility: "public",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ["&signer"],
      return: [],
    },
    {
      name: "transfer_admin_role",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "address"],
      return: [],
    },
  ],
  structs: [
    {
      name: "AdminStore",
      is_native: false,
      is_event: false,
      abilities: ["key"],
      generic_type_params: [],
      fields: [
        {
          name: "admin_address",
          type: "address",
        },
      ],
    },
  ],
} as const;
