// This file is generated by 'pnpm move:get_abi'. DO NOT EDIT MANUALLY.
export const ORACLE_USDC_ABI = {
  address: "0x91bf586a77ca2e15193f8068d0f7e4f5e43253fc724be1fbc5efb6134a544180",
  name: "oracle_usdc",
  friends: [
    "0x91bf586a77ca2e15193f8068d0f7e4f5e43253fc724be1fbc5efb6134a544180::oracles",
  ],
  exposed_functions: [
    {
      name: "get_total_supply",
      visibility: "friend",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: ["u64"],
    },
  ],
  structs: [],
} as const;
