// This file is generated by 'pnpm move:get_abi'. DO NOT EDIT MANUALLY.
export const ORACLE_REGISTRY_ABI = {
  address: "0x91bf586a77ca2e15193f8068d0f7e4f5e43253fc724be1fbc5efb6134a544180",
  name: "oracle_registry",
  friends: [],
  exposed_functions: [
    {
      name: "is_oracle_active",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["0x1::string::String"],
      return: ["bool"],
    },
    {
      name: "register_oracle",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "0x1::string::String", "0x1::string::String"],
      return: [],
    },
    {
      name: "set_global_pause",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "bool"],
      return: [],
    },
    {
      name: "set_oracle_status",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "0x1::string::String", "bool"],
      return: [],
    },
  ],
  structs: [
    {
      name: "OracleInfo",
      is_native: false,
      is_event: false,
      abilities: ["copy", "drop", "store"],
      generic_type_params: [],
      fields: [
        {
          name: "id",
          type: "0x1::string::String",
        },
        {
          name: "protocol_name",
          type: "0x1::string::String",
        },
        {
          name: "is_active",
          type: "bool",
        },
      ],
    },
    {
      name: "OracleRegistry",
      is_native: false,
      is_event: false,
      abilities: ["key"],
      generic_type_params: [],
      fields: [
        {
          name: "oracles",
          type: "0x1::table::Table<0x1::string::String, 0x91bf586a77ca2e15193f8068d0f7e4f5e43253fc724be1fbc5efb6134a544180::oracle_registry::OracleInfo>",
        },
        {
          name: "is_globally_paused",
          type: "bool",
        },
      ],
    },
  ],
} as const;
