// This file is generated by 'pnpm move:get_abi'. DO NOT EDIT MANUALLY.
export const ORACLES_ABI = {
  address: "0x91bf586a77ca2e15193f8068d0f7e4f5e43253fc724be1fbc5efb6134a544180",
  name: "oracles",
  friends: [
    "0x91bf586a77ca2e15193f8068d0f7e4f5e43253fc724be1fbc5efb6134a544180::verifi_protocol",
    "0x91bf586a77ca2e15193f8068d0f7e4f5e43253fc724be1fbc5efb6134a544180::verifi_resolvers",
  ],
  exposed_functions: [
    {
      name: "fetch_data",
      visibility: "friend",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["0x1::string::String", "address"],
      return: ["u64"],
    },
  ],
  structs: [],
} as const;
