// This file is generated by 'pnpm move:get_abi'. DO NOT EDIT MANUALLY.
export const VERIFI_PROTOCOL_ABI = {
  address: "0xccaa847ed88237e68ad62359f15bc748021b70a5bc1777241a230e270e6a0ef8",
  name: "verifi_protocol",
  friends: [],
  exposed_functions: [
    {
      name: "create_market",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [
        "&signer",
        "0x1::string::String",
        "u64",
        "address",
        "address",
        "0x1::string::String",
        "u64",
        "u8",
      ],
      return: [],
    },
  ],
  structs: [
    {
      name: "Market",
      is_native: false,
      is_event: false,
      abilities: ["key"],
      generic_type_params: [],
      fields: [
        {
          name: "description",
          type: "0x1::string::String",
        },
        {
          name: "resolver",
          type: "address",
        },
        {
          name: "resolution_timestamp",
          type: "u64",
        },
        {
          name: "status",
          type: "u8",
        },
        {
          name: "target_address",
          type: "address",
        },
        {
          name: "target_function",
          type: "0x1::string::String",
        },
        {
          name: "target_value",
          type: "u64",
        },
        {
          name: "operator",
          type: "u8",
        },
        {
          name: "pool_yes_tokens",
          type: "u64",
        },
        {
          name: "pool_no_tokens",
          type: "u64",
        },
        {
          name: "yes_token_metadata",
          type: "0x1::object::Object<0x1::fungible_asset::Metadata>",
        },
        {
          name: "no_token_metadata",
          type: "0x1::object::Object<0x1::fungible_asset::Metadata>",
        },
      ],
    },
    {
      name: "MarketCreatedEvent",
      is_native: false,
      is_event: false,
      abilities: ["drop", "store"],
      generic_type_params: [],
      fields: [
        {
          name: "market_address",
          type: "address",
        },
        {
          name: "creator",
          type: "address",
        },
        {
          name: "description",
          type: "0x1::string::String",
        },
        {
          name: "resolution_timestamp",
          type: "u64",
        },
      ],
    },
    {
      name: "MarketFactory",
      is_native: false,
      is_event: false,
      abilities: ["key"],
      generic_type_params: [],
      fields: [
        {
          name: "market_count",
          type: "u64",
        },
        {
          name: "markets",
          type: "vector<0x1::object::Object<0xccaa847ed88237e68ad62359f15bc748021b70a5bc1777241a230e270e6a0ef8::verifi_protocol::Market>>",
        },
        {
          name: "creation_events",
          type: "0x1::event::EventHandle<0xccaa847ed88237e68ad62359f15bc748021b70a5bc1777241a230e270e6a0ef8::verifi_protocol::MarketCreatedEvent>",
        },
      ],
    },
    {
      name: "MarketFactoryController",
      is_native: false,
      is_event: false,
      abilities: ["key"],
      generic_type_params: [],
      fields: [
        {
          name: "extend_ref",
          type: "0x1::object::ExtendRef",
        },
      ],
    },
  ],
} as const;
