// This file is generated by 'pnpm move:get_abi'. DO NOT EDIT MANUALLY.
export const VERIFI_RESOLVERS_ABI = {
  address: "0x91bf586a77ca2e15193f8068d0f7e4f5e43253fc724be1fbc5efb6134a544180",
  name: "verifi_resolvers",
  friends: [],
  exposed_functions: [
    {
      name: "resolve_market",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [
        "&signer",
        "0x1::object::Object<0x91bf586a77ca2e15193f8068d0f7e4f5e43253fc724be1fbc5efb6134a544180::verifi_protocol::Market>",
      ],
      return: [],
    },
  ],
  structs: [],
} as const;
