// This file is generated by 'pnpm move:get_abi'. DO NOT EDIT MANUALLY.
export const ACCESS_CONTROL_ABI = {
  address: "0x93bc73410f9345c6ff9c399c43913e7a7701a7331e375a70b0ba81ccca036674",
  name: "access_control",
  friends: [],
  exposed_functions: [
    {
      name: "assert_is_admin",
      visibility: "public",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ["&signer"],
      return: [],
    },
    {
      name: "is_admin",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address"],
      return: ["bool"],
    },
    {
      name: "transfer_admin_role",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "address"],
      return: [],
    },
  ],
  structs: [
    {
      name: "AdminStore",
      is_native: false,
      is_event: false,
      abilities: ["key"],
      generic_type_params: [],
      fields: [
        {
          name: "admin_address",
          type: "address",
        },
      ],
    },
  ],
} as const;
