// This file is generated by 'pnpm move:get_abi'. DO NOT EDIT MANUALLY.
export const ADVANCED_ABI = {
  address: "0x227a26b2dbd6093f6f779dcae84254f5dc40b461859a49b2eae6562db0434b15",
  name: "advanced",
  friends: [],
  exposed_functions: [
    {
      name: "swap",
      visibility: "public",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "&mut 0x1::bcs_stream::BCSStream", "address"],
      return: ["u64", "u64", "u64", "u64"],
    },
    {
      name: "add_campaign",
      visibility: "public",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "&mut 0x1::bcs_stream::BCSStream"],
      return: [],
    },
    {
      name: "add_liquidity",
      visibility: "public",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: [
        "&signer",
        "0x1::option::Option<u64>",
        "&mut 0x1::bcs_stream::BCSStream",
        "address",
      ],
      return: ["vector<u64>", "0x1::option::Option<u64>"],
    },
    {
      name: "campaign_reward_amount",
      visibility: "public",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: [
        "&0x227a26b2dbd6093f6f779dcae84254f5dc40b461859a49b2eae6562db0434b15::advanced::CampaignReward",
      ],
      return: ["u64"],
    },
    {
      name: "campaign_reward_token",
      visibility: "public",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: [
        "&0x227a26b2dbd6093f6f779dcae84254f5dc40b461859a49b2eae6562db0434b15::advanced::CampaignReward",
      ],
      return: ["address"],
    },
    {
      name: "collect_fee",
      visibility: "public",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "u64", "address"],
      return: ["vector<u64>"],
    },
    {
      name: "create_pool",
      visibility: "public",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "vector<address>", "u64", "address"],
      return: [],
    },
    {
      name: "pool_seed",
      visibility: "public",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ["vector<address>", "u64"],
      return: ["vector<u8>"],
    },
    {
      name: "pool_stop_campaign",
      visibility: "public",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "&mut 0x1::bcs_stream::BCSStream"],
      return: ["u64"],
    },
    {
      name: "remove_liquidity",
      visibility: "public",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "u64", "&mut 0x1::bcs_stream::BCSStream", "address"],
      return: [
        "vector<u64>",
        "0x1::option::Option<u64>",
        "vector<0x227a26b2dbd6093f6f779dcae84254f5dc40b461859a49b2eae6562db0434b15::advanced::CampaignReward>",
      ],
    },
    {
      name: "run_pool_op",
      visibility: "public",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "&mut 0x1::bcs_stream::BCSStream"],
      return: [],
    },
  ],
  structs: [
    {
      name: "Position",
      is_native: false,
      is_event: false,
      abilities: ["copy", "drop", "store"],
      generic_type_params: [],
      fields: [
        {
          name: "value",
          type: "vector<u64>",
        },
        {
          name: "fee",
          type: "vector<u64>",
        },
      ],
    },
    {
      name: "Added",
      is_native: false,
      is_event: true,
      abilities: ["drop", "store"],
      generic_type_params: [],
      fields: [
        {
          name: "dummy_field",
          type: "bool",
        },
      ],
    },
    {
      name: "Campaign",
      is_native: false,
      is_event: false,
      abilities: ["store"],
      generic_type_params: [],
      fields: [
        {
          name: "campaign_idx",
          type: "u64",
        },
        {
          name: "token",
          type: "address",
        },
        {
          name: "total_amount",
          type: "u64",
        },
        {
          name: "distributed_amount",
          type: "u64",
        },
        {
          name: "distribution_rps",
          type: "u64",
        },
        {
          name: "last_distribution_at",
          type: "u64",
        },
        {
          name: "position_rewards",
          type: "vector<u64>",
        },
      ],
    },
    {
      name: "CampaignRegistry",
      is_native: false,
      is_event: false,
      abilities: ["key"],
      generic_type_params: [],
      fields: [
        {
          name: "campaigns",
          type: "vector<0x227a26b2dbd6093f6f779dcae84254f5dc40b461859a49b2eae6562db0434b15::advanced::Campaign>",
        },
        {
          name: "campaigns_counter",
          type: "u64",
        },
      ],
    },
    {
      name: "CampaignReward",
      is_native: false,
      is_event: false,
      abilities: ["copy", "drop", "store"],
      generic_type_params: [],
      fields: [
        {
          name: "token",
          type: "address",
        },
        {
          name: "amount",
          type: "u64",
        },
      ],
    },
    {
      name: "CollectedFee",
      is_native: false,
      is_event: true,
      abilities: ["drop", "store"],
      generic_type_params: [],
      fields: [
        {
          name: "dummy_field",
          type: "bool",
        },
      ],
    },
    {
      name: "Created",
      is_native: false,
      is_event: true,
      abilities: ["drop", "store"],
      generic_type_params: [],
      fields: [
        {
          name: "dummy_field",
          type: "bool",
        },
      ],
    },
    {
      name: "PoolState",
      is_native: false,
      is_event: false,
      abilities: ["key"],
      generic_type_params: [],
      fields: [
        {
          name: "fee_rate",
          type: "u64",
        },
        {
          name: "total_value",
          type: "u64",
        },
        {
          name: "assets",
          type: "vector<address>",
        },
        {
          name: "positions",
          type: "0x1::ordered_map::OrderedMap<u64, 0x227a26b2dbd6093f6f779dcae84254f5dc40b461859a49b2eae6562db0434b15::advanced::Position>",
        },
        {
          name: "positions_count",
          type: "u64",
        },
      ],
    },
    {
      name: "Removed",
      is_native: false,
      is_event: true,
      abilities: ["drop", "store"],
      generic_type_params: [],
      fields: [
        {
          name: "dummy_field",
          type: "bool",
        },
      ],
    },
    {
      name: "Swapped",
      is_native: false,
      is_event: true,
      abilities: ["drop", "store"],
      generic_type_params: [],
      fields: [
        {
          name: "dummy_field",
          type: "bool",
        },
      ],
    },
  ],
} as const;
