// This file is generated by 'pnpm move:get_abi'. DO NOT EDIT MANUALLY.
export const APPROVAL_MOCKUP_ABI = {
  address: "0x227a26b2dbd6093f6f779dcae84254f5dc40b461859a49b2eae6562db0434b15",
  name: "approval_mockup",
  friends: [],
  exposed_functions: [
    {
      name: "approve",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "u64", "u64"],
      return: [],
    },
    {
      name: "execute_approved_trade",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "address", "u64", "bool"],
      return: [],
    },
    {
      name: "get_approval",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address"],
      return: ["bool", "u64", "u64", "u64"],
    },
    {
      name: "get_remaining_allowance",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address"],
      return: ["u64"],
    },
    {
      name: "is_approved",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address"],
      return: ["bool"],
    },
    {
      name: "revoke_approval",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer"],
      return: [],
    },
  ],
  structs: [
    {
      name: "ApprovalGrantedEvent",
      is_native: false,
      is_event: true,
      abilities: ["drop", "store"],
      generic_type_params: [],
      fields: [
        {
          name: "user",
          type: "address",
        },
        {
          name: "max_amount",
          type: "u64",
        },
        {
          name: "expires_at",
          type: "u64",
        },
      ],
    },
    {
      name: "ApprovalRevokedEvent",
      is_native: false,
      is_event: true,
      abilities: ["drop", "store"],
      generic_type_params: [],
      fields: [
        {
          name: "user",
          type: "address",
        },
      ],
    },
    {
      name: "TradeExecutedEvent",
      is_native: false,
      is_event: true,
      abilities: ["drop", "store"],
      generic_type_params: [],
      fields: [
        {
          name: "user",
          type: "address",
        },
        {
          name: "amount",
          type: "u64",
        },
        {
          name: "action",
          type: "vector<u8>",
        },
      ],
    },
    {
      name: "UserApproval",
      is_native: false,
      is_event: false,
      abilities: ["key"],
      generic_type_params: [],
      fields: [
        {
          name: "max_amount_per_trade",
          type: "u64",
        },
        {
          name: "expires_at",
          type: "u64",
        },
        {
          name: "total_spent",
          type: "u64",
        },
        {
          name: "is_active",
          type: "bool",
        },
      ],
    },
  ],
} as const;
