// This file is generated by 'pnpm move:get_abi'. DO NOT EDIT MANUALLY.
export const BASIC_ABI = {
  address: "0x227a26b2dbd6093f6f779dcae84254f5dc40b461859a49b2eae6562db0434b15",
  name: "basic",
  friends: [],
  exposed_functions: [
    {
      name: "swap",
      visibility: "public",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "&mut 0x1::bcs_stream::BCSStream", "address"],
      return: ["bool", "u64", "u64"],
    },
    {
      name: "add_liquidity",
      visibility: "public",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: [
        "&signer",
        "0x1::option::Option<u64>",
        "&mut 0x1::bcs_stream::BCSStream",
        "address",
      ],
      return: ["vector<u64>", "0x1::option::Option<u64>"],
    },
    {
      name: "create_pool",
      visibility: "public",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "vector<address>", "u64", "address"],
      return: [],
    },
    {
      name: "pool_seed",
      visibility: "public",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ["vector<address>", "u64"],
      return: ["vector<u8>"],
    },
    {
      name: "remove_liquidity",
      visibility: "public",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "u64", "&mut 0x1::bcs_stream::BCSStream", "address"],
      return: ["vector<u64>", "0x1::option::Option<u64>"],
    },
  ],
  structs: [
    {
      name: "Position",
      is_native: false,
      is_event: false,
      abilities: ["copy", "drop", "store"],
      generic_type_params: [],
      fields: [
        {
          name: "value",
          type: "u64",
        },
      ],
    },
    {
      name: "Added",
      is_native: false,
      is_event: true,
      abilities: ["drop", "store"],
      generic_type_params: [],
      fields: [
        {
          name: "dummy_field",
          type: "bool",
        },
      ],
    },
    {
      name: "Created",
      is_native: false,
      is_event: true,
      abilities: ["drop", "store"],
      generic_type_params: [],
      fields: [
        {
          name: "dummy_field",
          type: "bool",
        },
      ],
    },
    {
      name: "PoolState",
      is_native: false,
      is_event: false,
      abilities: ["key"],
      generic_type_params: [],
      fields: [
        {
          name: "state",
          type: "u64",
        },
        {
          name: "amounts",
          type: "vector<u64>",
        },
        {
          name: "positions",
          type: "0x1::ordered_map::OrderedMap<u64, 0x227a26b2dbd6093f6f779dcae84254f5dc40b461859a49b2eae6562db0434b15::basic::Position>",
        },
        {
          name: "positions_count",
          type: "u64",
        },
      ],
    },
    {
      name: "Removed",
      is_native: false,
      is_event: true,
      abilities: ["drop", "store"],
      generic_type_params: [],
      fields: [
        {
          name: "dummy_field",
          type: "bool",
        },
      ],
    },
    {
      name: "Swapped",
      is_native: false,
      is_event: true,
      abilities: ["drop", "store"],
      generic_type_params: [],
      fields: [
        {
          name: "dummy_field",
          type: "bool",
        },
      ],
    },
  ],
} as const;
