// This file is generated by 'pnpm move:get_abi'. DO NOT EDIT MANUALLY.
export const ORACLE_APTOS_BALANCE_ABI = {
  address: "0x227a26b2dbd6093f6f779dcae84254f5dc40b461859a49b2eae6562db0434b15",
  name: "oracle_aptos_balance",
  friends: [
    "0x227a26b2dbd6093f6f779dcae84254f5dc40b461859a49b2eae6562db0434b15::oracles",
  ],
  exposed_functions: [
    {
      name: "get_value",
      visibility: "friend",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address"],
      return: ["u64"],
    },
  ],
  structs: [],
} as const;
