// This file is generated by 'pnpm move:get_abi'. DO NOT EDIT MANUALLY.
export const ORACLES_ABI = {
  address: "0x227a26b2dbd6093f6f779dcae84254f5dc40b461859a49b2eae6562db0434b15",
  name: "oracles",
  friends: [
    "0x227a26b2dbd6093f6f779dcae84254f5dc40b461859a49b2eae6562db0434b15::verifi_protocol",
    "0x227a26b2dbd6093f6f779dcae84254f5dc40b461859a49b2eae6562db0434b15::verifi_resolvers",
  ],
  exposed_functions: [
    {
      name: "fetch_data",
      visibility: "friend",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["0x1::string::String", "address"],
      return: ["u64"],
    },
  ],
  structs: [],
} as const;
