// This file is generated by 'pnpm move:get_abi'. DO NOT EDIT MANUALLY.
export const ORACLE_USDC_ABI = {
  address: "0x93bc73410f9345c6ff9c399c43913e7a7701a7331e375a70b0ba81ccca036674",
  name: "oracle_usdc",
  friends: [
    "0x93bc73410f9345c6ff9c399c43913e7a7701a7331e375a70b0ba81ccca036674::oracles",
  ],
  exposed_functions: [
    {
      name: "get_total_supply",
      visibility: "friend",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: ["u64"],
    },
  ],
  structs: [],
} as const;
