// This file is generated by 'pnpm move:get_abi'. DO NOT EDIT MANUALLY.
export const ORACLES_ABI = {
  address: "0x93bc73410f9345c6ff9c399c43913e7a7701a7331e375a70b0ba81ccca036674",
  name: "oracles",
  friends: [
    "0x93bc73410f9345c6ff9c399c43913e7a7701a7331e375a70b0ba81ccca036674::verifi_protocol",
    "0x93bc73410f9345c6ff9c399c43913e7a7701a7331e375a70b0ba81ccca036674::verifi_resolvers",
  ],
  exposed_functions: [
    {
      name: "fetch_data",
      visibility: "friend",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["0x1::string::String", "address"],
      return: ["u64"],
    },
  ],
  structs: [],
} as const;
