// This file is generated by 'pnpm move:get_abi'. DO NOT EDIT MANUALLY.
export const POSITION_ABI = {
  address: "0x93bc73410f9345c6ff9c399c43913e7a7701a7331e375a70b0ba81ccca036674",
  name: "position",
  friends: [
    "0x93bc73410f9345c6ff9c399c43913e7a7701a7331e375a70b0ba81ccca036674::router",
  ],
  exposed_functions: [
    {
      name: "authorized_borrow",
      visibility: "friend",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "&signer", "address", "address"],
      return: [
        "0x93bc73410f9345c6ff9c399c43913e7a7701a7331e375a70b0ba81ccca036674::position::PositionMeta",
      ],
    },
    {
      name: "position_idx",
      visibility: "public",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: [
        "&0x93bc73410f9345c6ff9c399c43913e7a7701a7331e375a70b0ba81ccca036674::position::PositionMeta",
      ],
      return: ["u64"],
    },
    {
      name: "mint_position",
      visibility: "friend",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "u8", "address", "u64", "address"],
      return: ["address"],
    },
    {
      name: "burn_position",
      visibility: "friend",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "address"],
      return: [],
    },
    {
      name: "hook_type",
      visibility: "public",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: [
        "&0x93bc73410f9345c6ff9c399c43913e7a7701a7331e375a70b0ba81ccca036674::position::PositionMeta",
      ],
      return: ["u8"],
    },
    {
      name: "init_collection",
      visibility: "friend",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ["&signer"],
      return: [],
    },
    {
      name: "pool_id",
      visibility: "public",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: [
        "&0x93bc73410f9345c6ff9c399c43913e7a7701a7331e375a70b0ba81ccca036674::position::PositionMeta",
      ],
      return: ["address"],
    },
    {
      name: "position_meta",
      visibility: "public",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ["address"],
      return: [
        "0x93bc73410f9345c6ff9c399c43913e7a7701a7331e375a70b0ba81ccca036674::position::PositionMeta",
      ],
    },
  ],
  structs: [
    {
      name: "PositionMeta",
      is_native: false,
      is_event: false,
      abilities: ["copy", "drop", "store", "key"],
      generic_type_params: [],
      fields: [
        {
          name: "hook_type",
          type: "u8",
        },
        {
          name: "pool_addr",
          type: "address",
        },
        {
          name: "position_idx",
          type: "u64",
        },
      ],
    },
  ],
} as const;
