// This file is generated by 'pnpm move:get_abi'. DO NOT EDIT MANUALLY.
export const ROUTER_ABI = {
  address: "0x93bc73410f9345c6ff9c399c43913e7a7701a7331e375a70b0ba81ccca036674",
  name: "router",
  friends: [],
  exposed_functions: [
    {
      name: "swap",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "vector<u8>"],
      return: [],
    },
    {
      name: "add_liquidity",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "vector<u8>"],
      return: [],
    },
    {
      name: "collect_fee",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "vector<u8>"],
      return: [],
    },
    {
      name: "create_pool",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "vector<u8>"],
      return: [],
    },
    {
      name: "remove_liquidity",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "vector<u8>"],
      return: [],
    },
    {
      name: "create_pool_add_liquidity",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "vector<u8>"],
      return: [],
    },
    {
      name: "internal_add_liquidity",
      visibility: "friend",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "vector<u8>"],
      return: ["u64", "address"],
    },
  ],
  structs: [
    {
      name: "Swapped",
      is_native: false,
      is_event: true,
      abilities: ["drop", "store"],
      generic_type_params: [],
      fields: [
        {
          name: "pool_addr",
          type: "address",
        },
        {
          name: "assets",
          type: "vector<address>",
        },
        {
          name: "asset_in_index",
          type: "u64",
        },
        {
          name: "asset_out_index",
          type: "u64",
        },
        {
          name: "amount_in",
          type: "u64",
        },
        {
          name: "amount_out",
          type: "u64",
        },
        {
          name: "creator",
          type: "address",
        },
        {
          name: "ts",
          type: "u64",
        },
      ],
    },
    {
      name: "FeeCollected",
      is_native: false,
      is_event: true,
      abilities: ["drop", "store"],
      generic_type_params: [],
      fields: [
        {
          name: "pool_addr",
          type: "address",
        },
        {
          name: "hook_type",
          type: "u8",
        },
        {
          name: "position_idx",
          type: "u64",
        },
        {
          name: "assets",
          type: "vector<address>",
        },
        {
          name: "amounts",
          type: "vector<u64>",
        },
        {
          name: "creator",
          type: "address",
        },
        {
          name: "ts",
          type: "u64",
        },
      ],
    },
    {
      name: "LiquidityAdded",
      is_native: false,
      is_event: true,
      abilities: ["drop", "store"],
      generic_type_params: [],
      fields: [
        {
          name: "pool_addr",
          type: "address",
        },
        {
          name: "position_idx",
          type: "u64",
        },
        {
          name: "assets",
          type: "vector<address>",
        },
        {
          name: "amounts",
          type: "vector<u64>",
        },
        {
          name: "creator",
          type: "address",
        },
        {
          name: "ts",
          type: "u64",
        },
      ],
    },
    {
      name: "LiquidityRemoved",
      is_native: false,
      is_event: true,
      abilities: ["drop", "store"],
      generic_type_params: [],
      fields: [
        {
          name: "pool_addr",
          type: "address",
        },
        {
          name: "position_idx",
          type: "u64",
        },
        {
          name: "assets",
          type: "vector<address>",
        },
        {
          name: "amounts",
          type: "vector<u64>",
        },
        {
          name: "creator",
          type: "address",
        },
        {
          name: "ts",
          type: "u64",
        },
      ],
    },
    {
      name: "PoolCreated",
      is_native: false,
      is_event: true,
      abilities: ["drop", "store"],
      generic_type_params: [],
      fields: [
        {
          name: "pool_addr",
          type: "address",
        },
        {
          name: "hook_type",
          type: "u8",
        },
        {
          name: "assets",
          type: "vector<address>",
        },
        {
          name: "creator",
          type: "address",
        },
        {
          name: "ts",
          type: "u64",
        },
      ],
    },
    {
      name: "Manager",
      is_native: false,
      is_event: false,
      abilities: ["key"],
      generic_type_params: [],
      fields: [
        {
          name: "vault",
          type: "0x1::account::SignerCapability",
        },
        {
          name: "pools",
          type: "vector<address>",
        },
      ],
    },
    {
      name: "PoolCap",
      is_native: false,
      is_event: false,
      abilities: ["key"],
      generic_type_params: [],
      fields: [
        {
          name: "extend_ref",
          type: "0x1::object::ExtendRef",
        },
      ],
    },
  ],
} as const;
