// This file is generated by 'pnpm move:get_abi'. DO NOT EDIT MANUALLY.
export const SESSION_KEY_MOCKUP_ABI = {
  address: "0x227a26b2dbd6093f6f779dcae84254f5dc40b461859a49b2eae6562db0434b15",
  name: "session_key_mockup",
  friends: [],
  exposed_functions: [
    {
      name: "create_session",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "vector<u8>", "u64", "u64"],
      return: [],
    },
    {
      name: "execute_trade_with_session",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "address", "u64", "bool", "u64", "vector<u8>"],
      return: [],
    },
    {
      name: "get_session",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address"],
      return: ["bool", "vector<u8>", "u64", "u64", "u64"],
    },
    {
      name: "is_session_active",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address"],
      return: ["bool"],
    },
    {
      name: "revoke_session",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer"],
      return: [],
    },
  ],
  structs: [
    {
      name: "SessionCreatedEvent",
      is_native: false,
      is_event: true,
      abilities: ["drop", "store"],
      generic_type_params: [],
      fields: [
        {
          name: "user",
          type: "address",
        },
        {
          name: "session_public_key",
          type: "vector<u8>",
        },
        {
          name: "max_amount",
          type: "u64",
        },
        {
          name: "expires_at",
          type: "u64",
        },
      ],
    },
    {
      name: "SessionKey",
      is_native: false,
      is_event: false,
      abilities: ["key"],
      generic_type_params: [],
      fields: [
        {
          name: "session_public_key",
          type: "vector<u8>",
        },
        {
          name: "max_amount_per_trade",
          type: "u64",
        },
        {
          name: "expires_at",
          type: "u64",
        },
        {
          name: "total_spent",
          type: "u64",
        },
        {
          name: "is_active",
          type: "bool",
        },
      ],
    },
    {
      name: "SessionRevokedEvent",
      is_native: false,
      is_event: true,
      abilities: ["drop", "store"],
      generic_type_params: [],
      fields: [
        {
          name: "user",
          type: "address",
        },
      ],
    },
    {
      name: "TradeExecutedViaSessionEvent",
      is_native: false,
      is_event: true,
      abilities: ["drop", "store"],
      generic_type_params: [],
      fields: [
        {
          name: "user",
          type: "address",
        },
        {
          name: "amount",
          type: "u64",
        },
        {
          name: "action",
          type: "vector<u8>",
        },
      ],
    },
  ],
} as const;
