// This file is generated by 'pnpm move:get_abi'. DO NOT EDIT MANUALLY.
export const VAULT_ABI = {
  address: "0x227a26b2dbd6093f6f779dcae84254f5dc40b461859a49b2eae6562db0434b15",
  name: "vault",
  friends: [],
  exposed_functions: [
    {
      name: "swap",
      visibility: "public",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "&mut 0x1::bcs_stream::BCSStream", "address"],
      return: ["vector<u64>"],
    },
    {
      name: "deposit",
      visibility: "public",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: [
        "&signer",
        "0x1::option::Option<u64>",
        "&mut 0x1::bcs_stream::BCSStream",
        "address",
      ],
      return: ["vector<u64>", "0x1::option::Option<u64>"],
    },
    {
      name: "withdraw",
      visibility: "public",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "u64", "&mut 0x1::bcs_stream::BCSStream", "address"],
      return: ["vector<u64>", "0x1::option::Option<u64>"],
    },
    {
      name: "collect_fee",
      visibility: "public",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "address"],
      return: ["vector<u64>"],
    },
    {
      name: "create_pool",
      visibility: "public",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: [
        "&signer",
        "vector<address>",
        "u64",
        "&mut 0x1::bcs_stream::BCSStream",
        "address",
      ],
      return: [],
    },
    {
      name: "pool_seed",
      visibility: "public",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ["u8", "vector<address>"],
      return: ["vector<u8>"],
    },
  ],
  structs: [
    {
      name: "InsuranceSlot",
      is_native: false,
      is_event: false,
      abilities: ["copy", "drop", "store"],
      generic_type_params: [],
      fields: [
        {
          name: "amounts",
          type: "vector<u64>",
        },
        {
          name: "created_at",
          type: "u64",
        },
      ],
    },
    {
      name: "TimeLockedSlot",
      is_native: false,
      is_event: false,
      abilities: ["copy", "drop", "store"],
      generic_type_params: [],
      fields: [
        {
          name: "amounts",
          type: "vector<u64>",
        },
        {
          name: "created_at",
          type: "u64",
        },
        {
          name: "lock_until",
          type: "u64",
        },
      ],
    },
    {
      name: "Vault",
      is_native: false,
      is_event: false,
      abilities: ["key"],
      generic_type_params: [
        {
          constraints: [],
        },
      ],
      fields: [
        {
          name: "supported_assets",
          type: "vector<address>",
        },
        {
          name: "slots",
          type: "0x1::ordered_map::OrderedMap<u64, T0>",
        },
        {
          name: "slots_count",
          type: "u64",
        },
        {
          name: "fee",
          type: "u64",
        },
        {
          name: "fee_amounts",
          type: "vector<u64>",
        },
        {
          name: "creator",
          type: "address",
        },
      ],
    },
  ],
} as const;
