// This file is generated by 'pnpm move:get_abi'. DO NOT EDIT MANUALLY.
export const VERIFI_RESOLVERS_ABI = {
  address: "0x227a26b2dbd6093f6f779dcae84254f5dc40b461859a49b2eae6562db0434b15",
  name: "verifi_resolvers",
  friends: [],
  exposed_functions: [
    {
      name: "resolve_market",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [
        "&signer",
        "0x1::object::Object<0x227a26b2dbd6093f6f779dcae84254f5dc40b461859a49b2eae6562db0434b15::verifi_protocol::Market>",
      ],
      return: [],
    },
  ],
  structs: [],
} as const;
