// This file is generated by 'pnpm move:get_abi'. DO NOT EDIT MANUALLY.
export const VERIFI_PROTOCOL_ABI = {
  address: "0x227a26b2dbd6093f6f779dcae84254f5dc40b461859a49b2eae6562db0434b15",
  name: "verifi_protocol",
  friends: [
    "0x227a26b2dbd6093f6f779dcae84254f5dc40b461859a49b2eae6562db0434b15::verifi_resolvers",
  ],
  exposed_functions: [
    {
      name: "buy_shares",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [
        "&signer",
        "0x1::object::Object<0x227a26b2dbd6093f6f779dcae84254f5dc40b461859a49b2eae6562db0434b15::verifi_protocol::Market>",
        "u64",
        "bool",
      ],
      return: [],
    },
    {
      name: "create_market",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [
        "&signer",
        "0x1::string::String",
        "u64",
        "address",
        "0x1::string::String",
        "address",
        "0x1::string::String",
        "u64",
        "u8",
      ],
      return: [],
    },
    {
      name: "debug_check_outcome",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [
        "0x1::object::Object<0x227a26b2dbd6093f6f779dcae84254f5dc40b461859a49b2eae6562db0434b15::verifi_protocol::Market>",
      ],
      return: ["bool"],
    },
    {
      name: "debug_market_resolution_data",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [
        "0x1::object::Object<0x227a26b2dbd6093f6f779dcae84254f5dc40b461859a49b2eae6562db0434b15::verifi_protocol::Market>",
      ],
      return: ["u64", "u64", "u8", "u64", "u64", "u8"],
    },
    {
      name: "get_active_market_addresses",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: ["vector<address>"],
    },
    {
      name: "get_all_market_addresses",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: ["vector<address>"],
    },
    {
      name: "get_all_markets",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: [
        "vector<0x1::object::Object<0x227a26b2dbd6093f6f779dcae84254f5dc40b461859a49b2eae6562db0434b15::verifi_protocol::Market>>",
      ],
    },
    {
      name: "get_balances",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [
        "address",
        "0x1::object::Object<0x227a26b2dbd6093f6f779dcae84254f5dc40b461859a49b2eae6562db0434b15::verifi_protocol::Market>",
      ],
      return: ["u64", "u64"],
    },
    {
      name: "get_batch_market_summaries",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["vector<address>"],
      return: [
        "vector<0x227a26b2dbd6093f6f779dcae84254f5dc40b461859a49b2eae6562db0434b15::verifi_protocol::MarketSummary>",
      ],
    },
    {
      name: "get_fa_balance",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address", "address"],
      return: ["u64"],
    },
    {
      name: "get_factory_signer_address",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: ["address"],
    },
    {
      name: "get_factory_status",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: ["bool", "bool"],
    },
    {
      name: "get_market_counts",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: ["u64", "u64", "u64", "u64", "u64"],
    },
    {
      name: "get_market_info",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [
        "0x1::object::Object<0x227a26b2dbd6093f6f779dcae84254f5dc40b461859a49b2eae6562db0434b15::verifi_protocol::Market>",
      ],
      return: [
        "0x1::string::String",
        "address",
        "u64",
        "u8",
        "0x1::string::String",
      ],
    },
    {
      name: "get_market_resolution_data",
      visibility: "friend",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: [
        "0x1::object::Object<0x227a26b2dbd6093f6f779dcae84254f5dc40b461859a49b2eae6562db0434b15::verifi_protocol::Market>",
      ],
      return: ["0x1::string::String", "address", "u64", "u8", "u64"],
    },
    {
      name: "get_market_state",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [
        "0x1::object::Object<0x227a26b2dbd6093f6f779dcae84254f5dc40b461859a49b2eae6562db0434b15::verifi_protocol::Market>",
      ],
      return: ["u8", "u64", "u64", "u64", "u64"],
    },
    {
      name: "get_market_status",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [
        "0x1::object::Object<0x227a26b2dbd6093f6f779dcae84254f5dc40b461859a49b2eae6562db0434b15::verifi_protocol::Market>",
      ],
      return: ["u8"],
    },
    {
      name: "get_market_summary",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address"],
      return: [
        "0x227a26b2dbd6093f6f779dcae84254f5dc40b461859a49b2eae6562db0434b15::verifi_protocol::MarketSummary",
      ],
    },
    {
      name: "get_market_tokens",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [
        "0x1::object::Object<0x227a26b2dbd6093f6f779dcae84254f5dc40b461859a49b2eae6562db0434b15::verifi_protocol::Market>",
      ],
      return: [
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
      ],
    },
    {
      name: "get_market_view",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [
        "0x1::object::Object<0x227a26b2dbd6093f6f779dcae84254f5dc40b461859a49b2eae6562db0434b15::verifi_protocol::Market>",
      ],
      return: [
        "0x227a26b2dbd6093f6f779dcae84254f5dc40b461859a49b2eae6562db0434b15::verifi_protocol::MarketView",
      ],
    },
    {
      name: "get_protocol_stats",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: [
        "0x227a26b2dbd6093f6f779dcae84254f5dc40b461859a49b2eae6562db0434b15::verifi_protocol::ProtocolStats",
      ],
    },
    {
      name: "get_resolution_timestamp",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [
        "0x1::object::Object<0x227a26b2dbd6093f6f779dcae84254f5dc40b461859a49b2eae6562db0434b15::verifi_protocol::Market>",
      ],
      return: ["u64"],
    },
    {
      name: "get_resolved_market_addresses",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: ["vector<address>"],
    },
    {
      name: "get_token_addresses",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [
        "0x1::object::Object<0x227a26b2dbd6093f6f779dcae84254f5dc40b461859a49b2eae6562db0434b15::verifi_protocol::Market>",
      ],
      return: ["address", "address"],
    },
    {
      name: "get_user_active_markets",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address"],
      return: ["vector<address>"],
    },
    {
      name: "get_user_portfolio_value",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address"],
      return: [
        "0x227a26b2dbd6093f6f779dcae84254f5dc40b461859a49b2eae6562db0434b15::verifi_protocol::PortfolioValue",
      ],
    },
    {
      name: "get_user_position",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address", "address"],
      return: [
        "0x227a26b2dbd6093f6f779dcae84254f5dc40b461859a49b2eae6562db0434b15::verifi_protocol::UserPosition",
      ],
    },
    {
      name: "get_user_positions",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address", "vector<address>"],
      return: [
        "vector<0x227a26b2dbd6093f6f779dcae84254f5dc40b461859a49b2eae6562db0434b15::verifi_protocol::UserPosition>",
      ],
    },
    {
      name: "is_factory_initialized",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: ["bool"],
    },
    {
      name: "redeem_winnings",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [
        "&signer",
        "0x1::object::Object<0x227a26b2dbd6093f6f779dcae84254f5dc40b461859a49b2eae6562db0434b15::verifi_protocol::Market>",
        "u64",
      ],
      return: [],
    },
    {
      name: "resolve_market",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [
        "&signer",
        "0x1::object::Object<0x227a26b2dbd6093f6f779dcae84254f5dc40b461859a49b2eae6562db0434b15::verifi_protocol::Market>",
        "bool",
      ],
      return: [],
    },
    {
      name: "sell_shares",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [
        "&signer",
        "0x1::object::Object<0x227a26b2dbd6093f6f779dcae84254f5dc40b461859a49b2eae6562db0434b15::verifi_protocol::Market>",
        "u64",
        "bool",
      ],
      return: [],
    },
    {
      name: "update_market_status_from_resolver",
      visibility: "friend",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: [
        "0x1::object::Object<0x227a26b2dbd6093f6f779dcae84254f5dc40b461859a49b2eae6562db0434b15::verifi_protocol::Market>",
        "u64",
        "u64",
        "u8",
      ],
      return: [],
    },
  ],
  structs: [
    {
      name: "Market",
      is_native: false,
      is_event: false,
      abilities: ["key"],
      generic_type_params: [],
      fields: [
        {
          name: "description",
          type: "0x1::string::String",
        },
        {
          name: "resolver",
          type: "address",
        },
        {
          name: "resolution_timestamp",
          type: "u64",
        },
        {
          name: "status",
          type: "u8",
        },
        {
          name: "oracle_id",
          type: "0x1::string::String",
        },
        {
          name: "target_address",
          type: "address",
        },
        {
          name: "target_function",
          type: "0x1::string::String",
        },
        {
          name: "target_value",
          type: "u64",
        },
        {
          name: "operator",
          type: "u8",
        },
        {
          name: "pool_yes_tokens",
          type: "u64",
        },
        {
          name: "pool_no_tokens",
          type: "u64",
        },
        {
          name: "total_supply_yes",
          type: "u64",
        },
        {
          name: "total_supply_no",
          type: "u64",
        },
        {
          name: "yes_token_metadata",
          type: "0x1::object::Object<0x1::fungible_asset::Metadata>",
        },
        {
          name: "no_token_metadata",
          type: "0x1::object::Object<0x1::fungible_asset::Metadata>",
        },
        {
          name: "yes_token_mint_ref",
          type: "0x1::fungible_asset::MintRef",
        },
        {
          name: "yes_token_burn_ref",
          type: "0x1::fungible_asset::BurnRef",
        },
        {
          name: "no_token_mint_ref",
          type: "0x1::fungible_asset::MintRef",
        },
        {
          name: "no_token_burn_ref",
          type: "0x1::fungible_asset::BurnRef",
        },
        {
          name: "treasury_cap",
          type: "0x1::account::SignerCapability",
        },
        {
          name: "shares_minted_events",
          type: "0x1::event::EventHandle<0x227a26b2dbd6093f6f779dcae84254f5dc40b461859a49b2eae6562db0434b15::verifi_protocol::SharesMintedEvent>",
        },
        {
          name: "market_resolved_events",
          type: "0x1::event::EventHandle<0x227a26b2dbd6093f6f779dcae84254f5dc40b461859a49b2eae6562db0434b15::verifi_protocol::MarketResolvedEvent>",
        },
        {
          name: "winnings_redeemed_events",
          type: "0x1::event::EventHandle<0x227a26b2dbd6093f6f779dcae84254f5dc40b461859a49b2eae6562db0434b15::verifi_protocol::WinningsRedeemedEvent>",
        },
        {
          name: "shares_sold_events",
          type: "0x1::event::EventHandle<0x227a26b2dbd6093f6f779dcae84254f5dc40b461859a49b2eae6562db0434b15::verifi_protocol::SharesSoldEvent>",
        },
      ],
    },
    {
      name: "MarketCreatedEvent",
      is_native: false,
      is_event: true,
      abilities: ["drop", "store"],
      generic_type_params: [],
      fields: [
        {
          name: "market_address",
          type: "address",
        },
        {
          name: "creator",
          type: "address",
        },
        {
          name: "description",
          type: "0x1::string::String",
        },
        {
          name: "resolution_timestamp",
          type: "u64",
        },
      ],
    },
    {
      name: "MarketFactory",
      is_native: false,
      is_event: false,
      abilities: ["key"],
      generic_type_params: [],
      fields: [
        {
          name: "market_count",
          type: "u64",
        },
        {
          name: "markets",
          type: "vector<0x1::object::Object<0x227a26b2dbd6093f6f779dcae84254f5dc40b461859a49b2eae6562db0434b15::verifi_protocol::Market>>",
        },
        {
          name: "creation_events",
          type: "0x1::event::EventHandle<0x227a26b2dbd6093f6f779dcae84254f5dc40b461859a49b2eae6562db0434b15::verifi_protocol::MarketCreatedEvent>",
        },
        {
          name: "protocol_treasury_cap",
          type: "0x1::account::SignerCapability",
        },
      ],
    },
    {
      name: "MarketFactoryController",
      is_native: false,
      is_event: false,
      abilities: ["key"],
      generic_type_params: [],
      fields: [
        {
          name: "extend_ref",
          type: "0x1::object::ExtendRef",
        },
      ],
    },
    {
      name: "MarketResolvedEvent",
      is_native: false,
      is_event: true,
      abilities: ["drop", "store"],
      generic_type_params: [],
      fields: [
        {
          name: "market_address",
          type: "address",
        },
        {
          name: "outcome_is_yes",
          type: "bool",
        },
      ],
    },
    {
      name: "MarketSummary",
      is_native: false,
      is_event: false,
      abilities: ["drop"],
      generic_type_params: [],
      fields: [
        {
          name: "market_address",
          type: "address",
        },
        {
          name: "description",
          type: "0x1::string::String",
        },
        {
          name: "status",
          type: "u8",
        },
        {
          name: "resolution_timestamp",
          type: "u64",
        },
        {
          name: "yes_price",
          type: "u64",
        },
        {
          name: "no_price",
          type: "u64",
        },
        {
          name: "yes_supply",
          type: "u64",
        },
        {
          name: "no_supply",
          type: "u64",
        },
        {
          name: "total_supply",
          type: "u64",
        },
        {
          name: "pool_yes_tokens",
          type: "u64",
        },
        {
          name: "pool_no_tokens",
          type: "u64",
        },
      ],
    },
    {
      name: "MarketView",
      is_native: false,
      is_event: false,
      abilities: ["drop", "store"],
      generic_type_params: [],
      fields: [
        {
          name: "description",
          type: "0x1::string::String",
        },
        {
          name: "resolution_timestamp",
          type: "u64",
        },
        {
          name: "status",
          type: "u8",
        },
        {
          name: "pool_yes_tokens",
          type: "u64",
        },
        {
          name: "pool_no_tokens",
          type: "u64",
        },
        {
          name: "total_supply_yes",
          type: "u64",
        },
        {
          name: "total_supply_no",
          type: "u64",
        },
      ],
    },
    {
      name: "PortfolioValue",
      is_native: false,
      is_event: false,
      abilities: ["drop"],
      generic_type_params: [],
      fields: [
        {
          name: "total_positions",
          type: "u64",
        },
        {
          name: "total_value_yes",
          type: "u64",
        },
        {
          name: "total_value_no",
          type: "u64",
        },
        {
          name: "total_value",
          type: "u64",
        },
        {
          name: "market_count",
          type: "u64",
        },
      ],
    },
    {
      name: "ProtocolStats",
      is_native: false,
      is_event: false,
      abilities: ["drop"],
      generic_type_params: [],
      fields: [
        {
          name: "total_markets",
          type: "u64",
        },
        {
          name: "active_markets",
          type: "u64",
        },
        {
          name: "resolved_markets",
          type: "u64",
        },
        {
          name: "total_yes_supply",
          type: "u64",
        },
        {
          name: "total_no_supply",
          type: "u64",
        },
        {
          name: "total_supply",
          type: "u64",
        },
      ],
    },
    {
      name: "SharesMintedEvent",
      is_native: false,
      is_event: true,
      abilities: ["drop", "store"],
      generic_type_params: [],
      fields: [
        {
          name: "market_address",
          type: "address",
        },
        {
          name: "buyer",
          type: "address",
        },
        {
          name: "is_yes_outcome",
          type: "bool",
        },
        {
          name: "apt_amount_in",
          type: "u64",
        },
        {
          name: "shares_minted",
          type: "u64",
        },
      ],
    },
    {
      name: "SharesSoldEvent",
      is_native: false,
      is_event: true,
      abilities: ["drop", "store"],
      generic_type_params: [],
      fields: [
        {
          name: "market_address",
          type: "address",
        },
        {
          name: "seller",
          type: "address",
        },
        {
          name: "is_yes_outcome",
          type: "bool",
        },
        {
          name: "shares_burned",
          type: "u64",
        },
        {
          name: "apt_amount_out",
          type: "u64",
        },
      ],
    },
    {
      name: "UserPosition",
      is_native: false,
      is_event: false,
      abilities: ["drop"],
      generic_type_params: [],
      fields: [
        {
          name: "market_address",
          type: "address",
        },
        {
          name: "yes_balance",
          type: "u64",
        },
        {
          name: "no_balance",
          type: "u64",
        },
        {
          name: "yes_value",
          type: "u64",
        },
        {
          name: "no_value",
          type: "u64",
        },
        {
          name: "total_value",
          type: "u64",
        },
      ],
    },
    {
      name: "WinningsRedeemedEvent",
      is_native: false,
      is_event: true,
      abilities: ["drop", "store"],
      generic_type_params: [],
      fields: [
        {
          name: "market_address",
          type: "address",
        },
        {
          name: "redeemer",
          type: "address",
        },
        {
          name: "shares_burned",
          type: "u64",
        },
        {
          name: "apt_payout",
          type: "u64",
        },
      ],
    },
  ],
} as const;
