// This file is generated by 'pnpm move:get_abi'. DO NOT EDIT MANUALLY.
export const VERIFI_RESOLVERS_ABI = {
  address: "0x93bc73410f9345c6ff9c399c43913e7a7701a7331e375a70b0ba81ccca036674",
  name: "verifi_resolvers",
  friends: [],
  exposed_functions: [
    {
      name: "resolve_market",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [
        "&signer",
        "0x1::object::Object<0x93bc73410f9345c6ff9c399c43913e7a7701a7331e375a70b0ba81ccca036674::verifi_protocol::Market>",
      ],
      return: [],
    },
  ],
  structs: [],
} as const;
